version: '2'
services:
  rpc_proxy_1:
    build: .
    environment:
      - SETTINGS_DIR=/app/settings/nanostorm
    ports:
      - '15001:8080'
  rpc_proxy_2:
    build: .
    environment:
      - SETTINGS_DIR=/app/settings/nanostorm
    ports:
      - '15002:8080'
  http_proxy:
    image: nginx
    network_mode: host
    volumes:
      - ~/.nanostorm/logs/nginx:/var/log/nginx
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    environment:
     - NGINX_HOST=nanostorm.vault13.org
     - NGINX_PORT=80
